// <auto-generated />
using System;
using Dotnet.Mvc.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Dotnet.Mvc.Migrations
{
  [DbContext(typeof(RazorPagesMovieContext))]
  [Migration("20200928113902_InitialCreate")]
  partial class InitialCreate
  {
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
      modelBuilder
        .HasAnnotation("ProductVersion", "3.1.8");

      modelBuilder.Entity("Dotnet.Mvc.Models.Movie", b =>
        {
          b.Property<int>("ID")
            .ValueGeneratedOnAdd()
            .HasColumnType("INTEGER");

          b.Property<string>("Genre")
            .HasColumnType("TEXT");

          b.Property<decimal>("Price")
            .HasColumnType("TEXT");

          b.Property<DateTime>("ReleaseDate")
            .HasColumnType("TEXT");

          b.Property<string>("Title")
            .HasColumnType("TEXT");

          b.HasKey("ID");

          b.ToTable("Movie");
        });
#pragma warning restore 612, 618
    }
  }
}
